
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("b5737b9c-743b-4176-b822-398d9972a61a")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class orchard_mylightdisplayEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new orchard_mylightdisplayEntities object using the connection string found in the 'orchard_mylightdisplayEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=orchard_mylightdisplayEntities", "orchard_mylightdisplayEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new orchard_mylightdisplayEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "orchard_mylightdisplayEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new orchard_mylightdisplayEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "orchard_mylightdisplayEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MusicLogs() As ObjectSet(Of MusicLog)
        Get
            If (_MusicLogs Is Nothing) Then
                _MusicLogs = MyBase.CreateObjectSet(Of MusicLog)("MusicLogs")
            End If
            Return _MusicLogs
        End Get
    End Property

    Private _MusicLogs As ObjectSet(Of MusicLog)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MusicLogs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMusicLogs(ByVal musicLog As MusicLog)
        MyBase.AddObject("MusicLogs", musicLog)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="orchard_mylightdisplayModel", Name:="MusicLog")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MusicLog
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MusicLog object.
    ''' </summary>
    ''' <param name="logId">Initial value of the LogId property.</param>
    ''' <param name="song">Initial value of the Song property.</param>
    ''' <param name="artists">Initial value of the Artists property.</param>
    ''' <param name="year">Initial value of the Year property.</param>
    ''' <param name="length">Initial value of the Length property.</param>
    ''' <param name="dateStarted">Initial value of the DateStarted property.</param>
    ''' <param name="album">Initial value of the Album property.</param>
    ''' <param name="sequenceType">Initial value of the SequenceType property.</param>
    Public Shared Function CreateMusicLog(logId As Global.System.Int64, song As Global.System.String, artists As Global.System.String, year As Global.System.Int32, length As Global.System.String, dateStarted As Global.System.DateTime, album As Global.System.String, sequenceType As Global.System.Int32) As MusicLog
        Dim musicLog as MusicLog = New MusicLog
        musicLog.LogId = logId
        musicLog.Song = song
        musicLog.Artists = artists
        musicLog.Year = year
        musicLog.Length = length
        musicLog.DateStarted = dateStarted
        musicLog.Album = album
        musicLog.SequenceType = sequenceType
        Return musicLog
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LogId() As Global.System.Int64
        Get
            Return _LogId
        End Get
        Set
            If (_LogId <> Value) Then
                OnLogIdChanging(value)
                ReportPropertyChanging("LogId")
                _LogId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("LogId")
                OnLogIdChanged()
            End If
        End Set
    End Property

    Private _LogId As Global.System.Int64
    Private Partial Sub OnLogIdChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnLogIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Song() As Global.System.String
        Get
            Return _Song
        End Get
        Set
            OnSongChanging(value)
            ReportPropertyChanging("Song")
            _Song = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Song")
            OnSongChanged()
        End Set
    End Property

    Private _Song As Global.System.String
    Private Partial Sub OnSongChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSongChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Artists() As Global.System.String
        Get
            Return _Artists
        End Get
        Set
            OnArtistsChanging(value)
            ReportPropertyChanging("Artists")
            _Artists = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Artists")
            OnArtistsChanged()
        End Set
    End Property

    Private _Artists As Global.System.String
    Private Partial Sub OnArtistsChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnArtistsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Year() As Global.System.Int32
        Get
            Return _Year
        End Get
        Set
            OnYearChanging(value)
            ReportPropertyChanging("Year")
            _Year = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Year")
            OnYearChanged()
        End Set
    End Property

    Private _Year As Global.System.Int32
    Private Partial Sub OnYearChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnYearChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Length() As Global.System.String
        Get
            Return _Length
        End Get
        Set
            OnLengthChanging(value)
            ReportPropertyChanging("Length")
            _Length = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Length")
            OnLengthChanged()
        End Set
    End Property

    Private _Length As Global.System.String
    Private Partial Sub OnLengthChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLengthChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateStarted() As Global.System.DateTime
        Get
            Return _DateStarted
        End Get
        Set
            OnDateStartedChanging(value)
            ReportPropertyChanging("DateStarted")
            _DateStarted = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateStarted")
            OnDateStartedChanged()
        End Set
    End Property

    Private _DateStarted As Global.System.DateTime
    Private Partial Sub OnDateStartedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDateStartedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Album() As Global.System.String
        Get
            Return _Album
        End Get
        Set
            OnAlbumChanging(value)
            ReportPropertyChanging("Album")
            _Album = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Album")
            OnAlbumChanged()
        End Set
    End Property

    Private _Album As Global.System.String
    Private Partial Sub OnAlbumChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAlbumChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SequenceType() As Global.System.Int32
        Get
            Return _SequenceType
        End Get
        Set
            OnSequenceTypeChanging(value)
            ReportPropertyChanging("SequenceType")
            _SequenceType = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SequenceType")
            OnSequenceTypeChanged()
        End Set
    End Property

    Private _SequenceType As Global.System.Int32
    Private Partial Sub OnSequenceTypeChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSequenceTypeChanged()
    End Sub

    #End Region
End Class

#End Region

