'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MusicLogEntry
    Public Property Id As Long
    Public Property Song As String
    Public Property Artists As String
    Public Property Album As String
    Public Property Year As Integer
    Public Property Length As String
    Public Property DateStarted As Date
    Public Property SequenceType As Integer

End Class
